version: '3'

services:

  api:
    container_name: api # Name can be anything
    restart: always
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - frontend
    command: gunicorn -w 1 -b 172.18.0.2:8000 app:app

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "8001:8001"
    depends_on:
      - api
  frontend:
    container_name: react
    restart: always
    build: ./frontend
    ports:
      - "8010:8010"
    command: npm start
